#! /bin/bash 
#Perform a quick update on your instance:
sudo yum update -y

#Install git in your EC2 instance
sudo yum install git -y

# Install MySQL
sudo yum install mysql -y

# Download Java 17 to machine
wget https://download.java.net/java/GA/jdk17/0d483333a00540d886896bac774ff48b/35/GPL/openjdk-17_linux-x64_bin.tar.gz
# Extract using tar command 
tar xvf openjdk-17_linux-x64_bin.tar.gz
# Place the resultant folder in the /opt directory.
sudo mv jdk-17 /opt/
# Configure Java environment
sudo tee /etc/profile.d/jdk.sh <<EOF
export JAVA_HOME=/opt/jdk-17
export PATH=\$PATH:\$JAVA_HOME/bin
EOF
# source your profile
source /etc/profile.d/jdk.sh

## Install Maven ##
# Download Repo
sudo wget https://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
# Set the version of Apache Maven
sudo sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
# Use yum to install
sudo yum install -y apache-maven

## Install Docker ##
# Install Docker
sudo yum install docker -y
# Set the group memebership for the ec2-user to perform docker commands without sudo
sudo usermod -a -G docker ec2-user
# Reload a Linux user's group assignments to docker w/o logout
newgrp docker
# # Enable docker service at AMI boot time
sudo systemctl enable docker.service
# # Start the docker service
sudo systemctl start docker.service

#Run the application
docker run -p 8080:8080 springcommunity/spring-framework-petclinic